export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL   = "ADMIN_PRODUCT_FAIL";

export const ADMIN_NEW_PRODUCT_REQUEST = "ADMIN_NEW_PRODUCT_REQUEST";
export const ADMIN_NEW_PRODUCT_SUCCESS = "ADMIN_NEW_PRODUCT_SUCCESS";
export const ADMIN_NEW_PRODUCT_REST    = "ADMIN_NEW_PRODUCT_REST";
export const ADMIN_NEW_PRODUCT_FAIL    = "ADMIN_NEW_PRODUCT_FAIL";


export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST";
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_REST    = "ADMIN_DELETE_PRODUCT_REST";
export const ADMIN_DELETE_PRODUCT_FAIL    = "ADMIN_DELETE_PRODUCT_FAIL";

export const ADMIN_UPDATE_PRODUCT_REQUEST = "ADMIN_UPDATE_PRODUCT_REQUEST";
export const ADMIN_UPDATE_PRODUCT_SUCCESS = "ADMIN_UPDATE_PRODUCT_SUCCESS";
export const ADMIN_UPDATE_PRODUCT_REST    = "ADMIN_UPDATE_PRODUCT_REST";
export const ADMIN_UPDATE_PRODUCT_FAIL    = "ADMIN_UPDATE_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_REST = "NEW_REVIEW_REST";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
